name: msrk-v3
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - jupyter
  - nodejs>=16
  - npm
  - git
  - pip:
    - prisma>=0.11.0
    - psycopg2-binary>=2.9.0
    - pandas>=2.0.0
    - numpy>=1.24.0
    - scipy>=1.10.0
    - torch>=2.0.0
    - transformers>=4.30.0
    - optuna>=3.0.0
    - scikit-learn>=1.3.0
    - nixtla==0.2.8
    - fredapi>=0.5.0
    - yfinance>=0.2.0
    - pandas-datareader>=0.10.0
    - matplotlib>=3.7.0
    - seaborn>=0.12.0
    - plotly>=5.15.0
    - pyyaml>=6.0
    - python-dotenv>=1.0.0
    - tqdm>=4.65.0
    - requests>=2.31.0
    - black>=23.0.0
    - pytest>=7.4.0
    - google-generativeai>=0.3.0
    - ta>=0.10.0
    - quantlib>=1.31
